### ISSUE TITLE
Allow anyone who can change the project manager to edit Application Security

### ISSUE THREAD

**Issue by adamskrz** [adam-rms/adam-rms#620]
Neither a bug nor a feature request really.

We don't have the concept of a 'project manager' in the same way York does, with role allocations being done by the whole committee. This means we don't use the 'Applications visible to Project Manager Only' option, but can't disable it directly if the project manager is set to someone else.
While I guess this is intended behaviour, it can be worked around with the `PROJECTS:EDIT:LEAD` permission by assinging the lead to yourself, changing that option, then changing the lead back. 
It would make sense if the Application Security options were able to be changed by anyone with the `PROJECTS:EDIT:LEAD` permission, as this is something they already can do indirectly.

**Comment by Jbithell** [comment]
Thanks for opening this issue for discussion @adamskrz. We have had similar offline discussions about this a while back (would have been in the context of https://github.com/adam-rms/adam-rms/issues/116) as arguably project role applications are the only genuinely sensitive content that users put on the RMS. 

We chose the current approach because changing project manager is an action that shows up in the audit trail (under comments and history tab) - so it would be clear if someone had changed settings to access applications. 

I had a play and spotted an issue where by default if a new vacancy is created by anyone other than the PM then the role was locked to be PM visible only, and have corrected this in the attached PR. 

Would a workaround for your use case be to share application access with the whole committee when creating them? If so this PR allows that.

**Comment by adamskrz** [comment]
That makes sense! Yep, I think this PR would address the issue mostly (will just have to remind people to keep it unticked). 

Perhaps the wording underneath could be tweaked slightly - `blank to allow everyone to view applications` suggests that all uses will be able to see applications rather than just those with the `PROJECTS:PROJECT_CREW:EDIT:CREW_RECRUITMENT` permission, which put some of my commitee off it.
