### ISSUE TITLE
[FEATURE] Asset Management Features

### ISSUE THREAD

**Issue by qubered** [adam-rms/adam-rms#640]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

No, my feature request is not related to a specific problem, but rather it's about enhancing the functionality of Adam-RMS.

### Describe the solution you'd like

I would like to see the following features added to Adam-RMS to enhance its asset management capabilities:

1. **Customizable Barcodes**: The ability to set custom barcode prefixes and lengths for assets, allowing for formats like "AST0001." This would facilitate migration from other platforms with specific barcode formats.
2. **Default Locations**: The option to assign default locations to assets, such as "Shelf A," for easy reference to where items are typically stored. This would function similarly to how Snipe-IT handles default locations.
3. **Scheduled Audits**: A feature that allows setting up routine audits for assets, prompting maintenance checks or updates every defined period (e.g., 12 months). This would be useful for ensuring compliance, such as PAT testing.
4. **Detailed Asset Information**: The ability to add comprehensive information to assets, including supplier, purchase cost, purchase date, order number, and warranty details.
5. **Asset Views**: Different views for assets, such as tables, lists, or grids, to provide more flexible ways of browsing and managing asset data.
6. **Bulk Import**: The capability to bulk import assets, which would facilitate transitioning large numbers of assets from systems like Snipe-IT to Adam-RMS.
7. **Custom Category Groups**: The ability to create custom category groups for assets, catering to various types such as props, costumes, or set pieces.
8. **Friendly Names**: The option to assign friendly names or nicknames to assets, allowing for easy identification and improved search functionality.

These features would make AdamRMS pretty much the perfect asset and rental management system for my use case!

### Describe alternatives you've considered

Currently I use SnipeIT for asset management, with a mix of manually handling projects with excel spreadsheets etc. I would love for the features to be considered so that I can have an all in one platform. Not needing an alternative 😅

### Anything else?

Snipe-IT has quite a few of the features I have mentioned above. I have attached a few images of what I am referring too. 

<img width="827" alt="Example1" src="https://github.com/adam-rms/adam-rms/assets/156985453/8cca6656-bf55-4da8-a0d4-b665617ed35d">
This shows detailed info of the asset, its friendly name, and default location features.
<img width="1121" alt="example2" src="https://github.com/adam-rms/adam-rms/assets/156985453/ae2edeba-557e-4e34-8c25-1aed4c70fa62">
This shows a list view of assets.

**Comment by qubered** [comment]
The location stuff seems to be already in the works looking at Issue #615 and PR #626 

I am not sure how it plans to be implemented but having the location updated when the asset is on a project, then auto returned to the default location when the assets are checked back in after a project is how I have it in my head.

**Comment by Jbithell** [comment]
Thanks @qubered for your feedback - it's really useful to hear from people on how they use the platform. 

Would you be able to open seperate feature requests for each item? Sorry I appreciate that may feel like a bit of a pain, but it allows other members of the community to comment on the ideas, and helps us triage them. 

I've also responded below to a few of your comments - if I've misunderstood what you meant please do open a github issue for the feature if I've said it exists and what exists isn't what you had in mind!

> 1. **Customizable Barcodes**: The ability to set custom barcode prefixes and lengths for assets, allowing for formats like "AST0001." This would facilitate migration from other platforms with specific barcode formats.

This was a feature of the mobile app, and still exists within the API but is not currently implemented in the dashboard UI

> 2. **Default Locations**: The option to assign default locations to assets, such as "Shelf A," for easy reference to where items are typically stored. This would function similarly to how Snipe-IT handles default locations.

This can be achieved with the [definable fields feature](https://adam-rms.com/docs/v1/user-guide/assets/new-assets/#asset-types). What we'd like to do in future is to extend this to business-wide definable fields which can be set as optional/required etc. for all assets, and allow you to filter by fields. Please could you [open a feature request](https://github.com/adam-rms/adam-rms/issues/new?assignees=&labels=enhancement&projects=&template=feature-request.yml&title=%5BFEATURE%5D+Default+Locations) for this? 

> 3. **Scheduled Audits**: A feature that allows setting up routine audits for assets, prompting maintenance checks or updates every defined period (e.g., 12 months). This would be useful for ensuring compliance, such as PAT testing.

Nice idea. You can achieve this manually through maintenance jobs at the moment, but you can't ask it to repeat. Please could you [open a feature request](https://github.com/adam-rms/adam-rms/issues/new?assignees=&labels=enhancement&projects=&template=feature-request.yml&title=%5BFEATURE%5D+Scheduled+Audits) for this? 

> 4. **Detailed Asset Information**: The ability to add comprehensive information to assets, including supplier, purchase cost, purchase date, order number, and warranty details.

This is what the definable fields feature was designed for, and you can supplement this with file uploads for warranty details etc.

> 5. **Asset Views**: Different views for assets, such as tables, lists, or grids, to provide more flexible ways of browsing and managing asset data.

This sounds like a great feature - a bit like a CRM? Please could you [open a feature request](https://github.com/adam-rms/adam-rms/issues/new?assignees=&labels=enhancement&projects=&template=feature-request.yml&title=%5BFEATURE%5D+CRM+Style+Views) for this? 

> 6. **Bulk Import**: The capability to bulk import assets, which would facilitate transitioning large numbers of assets from systems like Snipe-IT to Adam-RMS.

This is an existing feature, but it can only be used by server administrators (so that would be yourself if self-hosting, or the support team if you were on the hosted package). We'd quite like to extend this to everyone, but it turned out the variety of formats that people hold the data in makes things really quite complicated. 

> 7. **Custom Category Groups**: The ability to create custom category groups for assets, catering to various types such as props, costumes, or set pieces.

You can find the custom categories in the business settings tab. [Docs](https://adam-rms.com/docs/v1/user-guide/business/business-settings/#custom-categories)

> 8. **Friendly Names**: The option to assign friendly names or nicknames to assets, allowing for easy identification and improved search functionality.

Could be a useful feature - please could you [open a feature request](https://github.com/adam-rms/adam-rms/issues/new?assignees=&labels=enhancement&projects=&template=feature-request.yml&title=%5BFEATURE%5D+Friendly+Names) for this?

**Comment by qubered** [comment]
On reflection, I didn't quite word the custom category feature request properly. I meant being able to create new parent categories. I will open a feature request for this too.

**Comment by qubered** [comment]
I have made feature requests for all the individual requests now :)

I'll close this issue.
